# Generated by Django 4.2.7 on 2025-12-04 06:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, verbose_name='شناسه مسیر')),
                ('name', models.CharField(max_length=100, verbose_name='نام مسیر')),
                ('type', models.CharField(choices=[('A', 'Alpha - شمال/جنوب'), ('B', 'Bravo - شمال/جنوب'), ('G', 'Golf - شرق/غرب'), ('R', 'Romeo - شرق/غرب')], max_length=1, verbose_name='نوع مسیر')),
                ('min_altitude', models.IntegerField(default=19000, verbose_name='حداقل ارتفاع (پا)')),
                ('max_altitude', models.IntegerField(default=41000, verbose_name='حداکثر ارتفاع (پا)')),
            ],
            options={
                'verbose_name': 'مسیر هوایی',
                'verbose_name_plural': 'مسیرهای هوایی',
                'db_table': 'airways',
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=5, unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('type', models.CharField(choices=[('FIX', 'Fix'), ('IAF', 'Initial Approach Fix'), ('FAF', 'Final Approach Fix'), ('MAP', 'Missed Approach Point')], default='FIX', max_length=10, verbose_name='نوع')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'Waypoint',
                'verbose_name_plural': 'Waypoints',
                'db_table': 'waypoints',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مسیر')),
                ('departure', models.CharField(db_index=True, max_length=10, verbose_name='فرودگاه مبدأ')),
                ('arrival', models.CharField(db_index=True, max_length=10, verbose_name='فرودگاه مقصد')),
                ('waypoints', models.JSONField(verbose_name='Waypoint ها')),
                ('coordinates', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='مختصات مسیر')),
                ('total_distance', models.FloatField(default=0, verbose_name='مسافت کل (NM)')),
                ('cruise_altitude', models.IntegerField(default=35000, verbose_name='ارتفاع کروز (ft)')),
                ('aircraft_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع هواپیما')),
                ('airline', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='شرکت هواپیمایی')),
                ('flight_number', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='شماره پرواز')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرواز')),
                ('fuel_required', models.FloatField(blank=True, null=True, verbose_name='سوخت مورد نیاز (kg)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_routes', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایشگر')),
            ],
            options={
                'verbose_name': 'مسیر',
                'verbose_name_plural': 'مسیرها',
                'db_table': 'routes',
                'indexes': [models.Index(fields=['departure'], name='routes_departu_f5ad8d_idx'), models.Index(fields=['arrival'], name='routes_arrival_b86db8_idx'), models.Index(fields=['created_at'], name='routes_created_e9932a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AirwaySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('distance', models.FloatField(verbose_name='Distance (km)')),
                ('base_altitude', models.IntegerField(default=19000, verbose_name='Base Altitude (ft)')),
                ('airway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='routes.airway')),
                ('from_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_starts', to='routes.waypoint')),
                ('to_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_ends', to='routes.waypoint')),
            ],
            options={
                'db_table': 'airway_segments',
                'ordering': ['airway', 'sequence'],
                'unique_together': {('airway', 'sequence')},
            },
        ),
    ]
