# Generated by Django 4.2.7 on 2025-12-04 11:04

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airway',
            options={'verbose_name': 'Airway', 'verbose_name_plural': 'Airways'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.RemoveField(
            model_name='airway',
            name='max_altitude',
        ),
        migrations.RemoveField(
            model_name='airway',
            name='min_altitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='route',
            name='cruise_altitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fuel_required',
        ),
        migrations.RemoveField(
            model_name='route',
            name='notes',
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='airway',
            name='identifier',
            field=models.CharField(max_length=10, verbose_name='Airway ID'),
        ),
        migrations.AlterField(
            model_name='airway',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Airway Name'),
        ),
        migrations.AlterField(
            model_name='airway',
            name='type',
            field=models.CharField(choices=[('A', 'Alpha - North/South'), ('B', 'Bravo - North/South'), ('G', 'Golf - East/West'), ('R', 'Romeo - East/West')], max_length=1, verbose_name='Airway Type'),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='route',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Route Name'),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_distance',
            field=models.FloatField(default=0, verbose_name='Total Distance (NM)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_routes', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=models.JSONField(verbose_name='Waypoints'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='identifier',
            field=models.CharField(max_length=5, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='type',
            field=models.CharField(choices=[('FIX', 'Fix'), ('IAF', 'Initial Approach Fix'), ('FAF', 'Final Approach Fix'), ('MAP', 'Missed Approach Point')], default='FIX', max_length=10, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['name'], name='routes_name_a2448e_idx'),
        ),
    ]
