# Generated by Django 4.2.7 on 2025-12-04 11:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_airway_options_alter_route_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airway',
            options={'ordering': ['identifier'], 'verbose_name': 'Airway', 'verbose_name_plural': 'Airways'},
        ),
        migrations.AlterModelOptions(
            name='waypoint',
            options={'ordering': ['identifier'], 'verbose_name': 'Waypoint', 'verbose_name_plural': 'Waypoints'},
        ),
        migrations.AlterField(
            model_name='route',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=models.JSONField(default=list, verbose_name='Waypoints'),
        ),
    ]
