# Generated by Django 4.2.7 on 2025-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_airway_options_alter_waypoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='arrival',
            field=models.CharField(db_index=True, max_length=4, verbose_name='Arrival (ICAO)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure',
            field=models.CharField(db_index=True, max_length=4, verbose_name='Departure (ICAO)'),
        ),
    ]
