# Generated by Django 4.2.7 on 2025-12-05 06:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_arrival_alter_route_departure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waypoint',
            options={'ordering': ['identifier'], 'verbose_name': 'نقطه ناوبری', 'verbose_name_plural': 'نقاط ناوبری'},
        ),
        migrations.AddField(
            model_name='waypoint',
            name='elevation',
            field=models.IntegerField(blank=True, null=True, verbose_name='ارتفاع (فوت)'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='فرکانس (MHz)'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='magnetic_variation',
            field=models.FloatField(blank=True, null=True, verbose_name='انحراف مغناطیسی (°)'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='source',
            field=models.CharField(choices=[('OURAIRPORTS', 'OurAirports'), ('AIP_IRAN', 'AIP ایران'), ('MANUAL', 'دستی')], default='OURAIRPORTS', max_length=50, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='airwaysegment',
            name='distance',
            field=models.FloatField(verbose_name='Distance (NM)'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='country',
            field=models.CharField(max_length=100, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='identifier',
            field=models.CharField(max_length=10, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='type',
            field=models.CharField(choices=[('AIRPORT', 'فرودگاه'), ('VOR', 'VOR/DME'), ('NDB', 'NDB'), ('FIX', 'Fix'), ('IAF', 'Initial Approach Fix'), ('FAF', 'Final Approach Fix'), ('MAWP', 'Missed Approach Waypoint'), ('RNAV', 'RNAV Waypoint'), ('DME', 'DME Only'), ('TACAN', 'TACAN'), ('VORTAC', 'VORTAC')], default='FIX', max_length=10, verbose_name='نوع'),
        ),
        migrations.AddIndex(
            model_name='waypoint',
            index=models.Index(fields=['type'], name='waypoints_type_8c87b1_idx'),
        ),
        migrations.AddIndex(
            model_name='waypoint',
            index=models.Index(fields=['country'], name='waypoints_country_f6c9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='waypoint',
            index=models.Index(fields=['is_active'], name='waypoints_is_acti_a7c84c_idx'),
        ),
    ]
