# Generated by Django 5.2.9 on 2025-12-07 05:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_waypoint_options_waypoint_elevation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInformationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True, verbose_name='شناسه FIR (مثال: OIIX)')),
                ('name', models.CharField(max_length=200, verbose_name='نام کامل FIR')),
                ('country', models.CharField(max_length=100, verbose_name='کشور صاحب FIR')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='کد کشور ISO')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='فرکانس\u200cهای اصلی')),
                ('emergency_frequency', models.CharField(default='121.5', max_length=50, verbose_name='فرکانس اضطراری')),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='مرز هوایی FIR')),
                ('upper_limit', models.IntegerField(default=99999, verbose_name='حد بالایی (فوت)')),
                ('lower_limit', models.IntegerField(default=0, verbose_name='حد پایینی (فوت)')),
                ('icao_region', models.CharField(choices=[('AS', 'Asia'), ('EU', 'Europe'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South America'), ('PA', 'Pacific'), ('ME', 'Middle East')], max_length=2, verbose_name='ناحیه ICAO')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
            ],
            options={
                'verbose_name': 'منطقه اطلاعات پرواز (FIR)',
                'verbose_name_plural': 'مناطق اطلاعات پرواز (FIR)',
                'db_table': 'fir_regions',
                'ordering': ['identifier'],
                'indexes': [models.Index(fields=['country'], name='fir_regions_country_c66835_idx'), models.Index(fields=['icao_region'], name='fir_regions_icao_re_9460f4_idx'), models.Index(fields=['is_active'], name='fir_regions_is_acti_712041_idx')],
            },
        ),
    ]
