# Generated by Django 5.2.9 on 2025-12-09 04:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_flightinformationregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinformationregion',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='مرز هوایی FIR'),
        ),
    ]
