# Generated by Django 5.2.9 on 2025-12-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_flightinformationregion_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinformationregion',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='کد کشور ISO'),
        ),
    ]
