# Generated by Django 5.2.9 on 2025-12-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_flightinformationregion_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='flight_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Flight Time (HH:MM)'),
        ),
    ]
