# Generated by Django 5.2.9 on 2025-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_route_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Route Name'),
        ),
    ]
