# Generated by Django 5.2.9 on 2026-01-02 06:54

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_alter_route_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightinformationregion',
            options={'ordering': ['identifier'], 'verbose_name': 'Flight Information Region (FIR)', 'verbose_name_plural': 'Flight Information Regions (FIR)'},
        ),
        migrations.AddField(
            model_name='route',
            name='version',
            field=models.CharField(blank=True, default='', help_text='User defined version, code, or number (e.g., v1, winter, emergency, 002)', max_length=50, verbose_name='Version/Code'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='FIR Boundary'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='ISO Country Code'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='emergency_frequency',
            field=models.CharField(default='121.5', max_length=50, verbose_name='Emergency Frequency'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, verbose_name='Main Frequencies'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='icao_region',
            field=models.CharField(choices=[('AS', 'Asia'), ('EU', 'Europe'), ('AF', 'Africa'), ('NA', 'North America'), ('SA', 'South America'), ('PA', 'Pacific'), ('ME', 'Middle East')], max_length=2, verbose_name='ICAO Region'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='identifier',
            field=models.CharField(max_length=10, unique=True, verbose_name='FIR Identifier (e.g., OIIX)'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='lower_limit',
            field=models.IntegerField(default=0, verbose_name='Lower Limit (ft)'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full FIR Name'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='upper_limit',
            field=models.IntegerField(default=99999, verbose_name='Upper Limit (ft)'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['version'], name='routes_version_55d307_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('departure', 'arrival', 'version'), name='unique_departure_arrival_version'),
        ),
    ]
