# Generated by Django 5.2.9 on 2026-01-04 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_alter_flightinformationregion_options_route_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waypoint',
            options={'ordering': ['identifier'], 'verbose_name': 'Waypoint', 'verbose_name_plural': 'Waypoints'},
        ),
        migrations.RemoveConstraint(
            model_name='route',
            name='unique_departure_arrival_version',
        ),
        migrations.AlterField(
            model_name='flightinformationregion',
            name='identifier',
            field=models.CharField(max_length=10, unique=True, verbose_name='FIR Identifier'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='elevation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elevation (ft)'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Frequency (MHz)'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='identifier',
            field=models.CharField(max_length=10, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='magnetic_variation',
            field=models.FloatField(blank=True, null=True, verbose_name='Magnetic Variation (°)'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='source',
            field=models.CharField(choices=[('OURAIRPORTS', 'OurAirports'), ('AIP', 'AIP'), ('MANUAL', 'Manual')], default='OURAIRPORTS', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='type',
            field=models.CharField(choices=[('AIRPORT', 'Airport'), ('VOR', 'VOR/DME'), ('NDB', 'NDB'), ('FIX', 'Fix'), ('IAF', 'Initial Approach Fix'), ('FAF', 'Final Approach Fix'), ('MAWP', 'Missed Approach Waypoint'), ('RNAV', 'RNAV Waypoint'), ('DME', 'DME Only'), ('TACAN', 'TACAN'), ('VORTAC', 'VORTAC')], default='FIX', max_length=10, verbose_name='Type'),
        ),
    ]
