# Generated by Django 5.2.9 on 2026-01-04 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_alter_waypoint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. False means route is deleted.', verbose_name='Active'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='routes_is_acti_9ece4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('departure', 'arrival', 'name', 'version'), name='unique_route_combination'),
        ),
    ]
