# Generated by Django 4.2.7 on 2025-11-27 04:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فرودگاه')),
                ('iata_code', models.CharField(max_length=3, unique=True, verbose_name='کد IATA')),
                ('icao_code', models.CharField(blank=True, max_length=4, verbose_name='کد ICAO')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت')),
                ('altitude', models.FloatField(default=0, verbose_name='ارتفاع از سطح دریا (متر)')),
                ('airport_type', models.CharField(choices=[('large_airport', 'فرودگاه بزرگ'), ('medium_airport', 'فرودگاه متوسط'), ('small_airport', 'فرودگاه کوچک')], max_length=20, verbose_name='نوع فرودگاه')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('runway_length', models.FloatField(blank=True, null=True, verbose_name='طول باند (متر)')),
            ],
            options={
                'verbose_name': 'فرودگاه',
                'verbose_name_plural': 'فرودگاه\u200cها',
                'db_table': 'airports',
            },
        ),
    ]
