# Generated by Django 4.2.7 on 2025-11-27 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_type',
            field=models.CharField(choices=[('large_airport', 'Large Airport'), ('medium_airport', 'Medium Airport'), ('small_airport', 'Small Airport')], max_length=20, verbose_name='Airport Type'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='altitude',
            field=models.FloatField(default=0, verbose_name='Altitude (m)'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='IATA Code'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='ICAO Code'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='runway_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Runway Length (m)'),
        ),
    ]
